# Generated by Django 4.1 on 2022-10-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="guest", managers=[],),
        migrations.AlterModelManagers(name="owner", managers=[],),
    ]
