# Generated by Django 4.1 on 2022-10-20 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="guest", managers=[],),
        migrations.AlterModelManagers(name="owner", managers=[],),
        migrations.RemoveField(model_name="guest", name="user_ptr",),
        migrations.RemoveField(model_name="owner", name="user_ptr",),
        migrations.AddField(
            model_name="guest",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guest",
            name="user",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="owner",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=3,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="owner",
            name="user",
            field=models.OneToOneField(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
