# Generated by Django 4.1 on 2022-09-29 14:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking",
            "0002_remove_owner_studio_remove_studio_guest_studio_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="guest",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelManagers(
            name="owner",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterField(
            model_name="guest",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="address",
                to="booking.address",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest",
                to="booking.guest",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio",
                to="booking.studio",
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
