# Generated by Django 4.1 on 2022-10-23 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_user_managers_remove_user_role"),
        ("booking", "0002_alter_guest_managers_alter_owner_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="booking.studio"
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("authentication.user",),
        ),
    ]
