# Generated by Django 4.1 on 2022-10-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_remove_employee_studio_employee_studio"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="studio",),
        migrations.AddField(
            model_name="employee",
            name="studio",
            field=models.ManyToManyField(to="booking.studio"),
        ),
    ]
