# Generated by Django 4.1 on 2022-09-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="birth_date",),
        migrations.RemoveField(model_name="user", name="email",),
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="last_name",),
    ]
