# Generated by Django 4.1 on 2022-09-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_birth_date_user_email_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=False, verbose_name="customer status"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=False, verbose_name="owner status"),
        ),
    ]
