# Generated by Django 4.1 on 2022-09-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_is_customer_user_is_owner"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_customer",),
        migrations.RemoveField(model_name="user", name="is_owner",),
    ]
