# Generated by Django 4.1 on 2022-10-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_user_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
