# Generated by Django 4.1 on 2022-10-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_usermanager_alter_user_managers"),
    ]

    operations = [
        migrations.DeleteModel(name="UserManager",),
    ]
