# Generated by Django 4.1 on 2022-10-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
        migrations.RemoveField(model_name="user", name="role",),
    ]
